ALTER TABLE visa_types ADD COLUMN IF NOT EXISTS ccl_template_path VARCHAR(255) DEFAULT NULL;
ALTER TABLE visa_types ADD COLUMN IF NOT EXISTS ccl_template_name VARCHAR(255) DEFAULT NULL;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'Success';
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS details TEXT;
