ALTER TABLE candidate_applications
  ADD COLUMN IF NOT EXISTS "cosNumber" VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "socCode" VARCHAR(50),
  ADD COLUMN IF NOT EXISTS "contractType" VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "workLocation" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "workingHours" VARCHAR(100);

ALTER TABLE sponsor_profiles
  ADD COLUMN IF NOT EXISTS "level2Users" JSONB;
