ALTER TABLE worker_events
  ADD COLUMN IF NOT EXISTS "reportedBy" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "evidenceFile" VARCHAR(500),
  ADD COLUMN IF NOT EXISTS "dateReportedToSms" TIMESTAMP WITH TIME ZONE;
