/**
 * EPiC Central Event Registry
 * Defines all system events that can be published to the Event Bus.
 */

export const EVENTS = {
  // Case Events
  CASE_CREATED: 'CASE_CREATED',
  CASE_ASSIGNED: 'CASE_ASSIGNED',
  CASE_REASSIGNED: 'CASE_REASSIGNED',
  CASE_STATUS_CHANGED: 'CASE_STATUS_CHANGED',
  CASE_ESCALATED: 'CASE_ESCALATED',
  CASE_CLOSED: 'CASE_CLOSED',

  // Document Events
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  DOCUMENT_REUPLOADED: 'DOCUMENT_REUPLOADED',
  DOCUMENT_APPROVED: 'DOCUMENT_APPROVED',
  DOCUMENT_REJECTED: 'DOCUMENT_REJECTED',
  DOCUMENT_APPROVAL_PENDING: 'DOCUMENT_APPROVAL_PENDING',
  ADDITIONAL_DOCUMENTS_REQUESTED: 'ADDITIONAL_DOCUMENTS_REQUESTED',

  // Payment Events
  PAYMENT_REQUEST_GENERATED: 'PAYMENT_REQUEST_GENERATED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',

  // Appointment Events
  APPOINTMENT_REQUESTED: 'APPOINTMENT_REQUESTED',
  APPOINTMENT_SCHEDULED: 'APPOINTMENT_SCHEDULED',
  APPOINTMENT_UPDATED: 'APPOINTMENT_UPDATED',
  APPOINTMENT_CANCELLED: 'APPOINTMENT_CANCELLED',

  // Change Request Events
  CHANGE_REQUEST_SUBMITTED: 'CHANGE_REQUEST_SUBMITTED',
  CHANGE_REQUEST_APPROVED: 'CHANGE_REQUEST_APPROVED',
  CHANGE_REQUEST_REJECTED: 'CHANGE_REQUEST_REJECTED',

  // Messaging
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',

  // Sponsor/Business Events
  COS_APPROVED: 'COS_APPROVED',
  LICENCE_APPROVED: 'LICENCE_APPROVED',

  // Application/Visa Events
  APPLICATION_SUBMITTED: 'APPLICATION_SUBMITTED',
  VISA_APPROVED: 'VISA_APPROVED',
  VISA_REJECTED: 'VISA_REJECTED',

  // User/Profile Events
  USER_CREATED: 'USER_CREATED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',

  // Task Events
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_UPDATED: 'TASK_UPDATED',

  // Workflow Events
  WORKFLOW_ERROR: 'WORKFLOW_ERROR',

  // Superadmin / Platform Events
  ORGANISATION_CREATED: 'ORGANISATION_CREATED',
  ORGANISATION_SUSPENDED: 'ORGANISATION_SUSPENDED',
  SUBSCRIPTION_EXPIRING: 'SUBSCRIPTION_EXPIRING',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  STORAGE_THRESHOLD_EXCEEDED: 'STORAGE_THRESHOLD_EXCEEDED',
  STRIPE_WEBHOOK_FAILURE: 'STRIPE_WEBHOOK_FAILURE',
  MICROSOFT_INTEGRATION_FAILURE: 'MICROSOFT_INTEGRATION_FAILURE',

  // Security & System Events
  SECURITY_ALERT: 'SECURITY_ALERT',
  SECURITY_INCIDENT: 'SECURITY_INCIDENT',
  SYSTEM_ERROR: 'SYSTEM_ERROR',
  API_FAILURE: 'API_FAILURE',
};
